---
 - name: install supported tools
   apt:
     name: haveged
     state: present
     update_cache: yes
   run_once: true
 - name: generate corosync authkey
   command: corosync-keygen
   run_once: true
 - name: uninstall haveged
   apt:
     name: haveged
     state: absent
   run_once: true
 - name: fetch keygen to local host /tmp
   fetch: src=/etc/corosync/authkey dest=/tmp/ flat=yes
   run_once: true
